name: Build and Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  dist:
    name: "Build distribution release."
    runs-on: ubuntu-latest

    steps:
      - name: "Checks out the repository."
        uses: "actions/checkout@v2"

      - name: "Setup NodeJS."
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: "Install NPM dependencies."
        run: npm install

      - name: "Build release: Stable"
        run: npm run build

      - name: "Remove files based on .distignore"
        run: |
          if [ -f .distignore ]; then
            cat .distignore | xargs rm -rf
          else
            echo ".distignore file not found."
          fi

      - name: "Create a Release Archive"
        run: |
          zip -r dblocks-codepro.zip .

      - name: "Extract Tag Name"
        id: extract_tag
        run: |
          ref="${GITHUB_REF##*/}"
          echo "Tag name is: $ref"
          echo "::set-output name=tag::$ref"

      - name: "Delete Existing Release by Tag Name"
        env:
          GITHUB_TOKEN: ${{ secrets.WPSCIPTSTOKEN }}
        run: |
          tag_name="${{ steps.extract_tag.outputs.tag }}"
          release_id=$(curl -H "Authorization: Bearer $GITHUB_TOKEN" -s https://api.github.com/repos/DBlocks-by-DPlugins/dblocks-codepro--dev/releases/tags/$tag_name | jq -r '.id')
          if [ -n "$release_id" ]; then
            curl -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" -s https://api.github.com/repos/DBlocks-by-DPlugins/dblocks-codepro--dev/releases/$release_id
          fi

      - name: "Create and Upload Release"
        uses: Hs1r1us/Release-AIO@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.WPSCIPTSTOKEN }}
        with:
          tag_name: "${{ steps.extract_tag.outputs.tag }}"
          asset_files: "./dblocks-codepro.zip"
