name: Transfer Files and Tag

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  clone_and_copy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Private Repository"
        uses: actions/checkout@v2
        with:
          repository: "DBlocks-by-DPlugins/dblocks-codepro--dev"
          token: ${{ secrets.WPSCIPTSTOKEN }}  # Token must have access to the private repo
          path: 'private-repo'

      - name: "Checkout Public Repository"
        uses: actions/checkout@v2
        with:
          repository: "DBlocks-by-DPlugins/dblocks-codepro"
          token: ${{ secrets.WPSCIPTSTOKEN }}  # Token must have access to the public repo
          path: 'public-repo'

      - name: "Copy files from Private to Public Repo"
        run: |
          cp -R private-repo/* public-repo/
          cd public-repo
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Sync files from private repository to public repository"
          git push origin main  # Push changes to the main branch of the public repository

      - name: "Copy Tags from Private to Public Repo"
        run: |
          cd private-repo
          git fetch --tags
          for tag in $(git tag); do
            if ! git rev-parse -q --verify "refs/tags/$tag"; then
              git push origin "$tag"  # Push the tag from the private repository to the public repository
            else
              echo "Tag $tag already exists. Skipping..."
            fi
          done
