name: Build and Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    name: "Build distribution release."
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Private Repo"
        uses: actions/checkout@v2
        with:
          path: 'private-repo'

      - name: "Setup NodeJS."
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: "Install NPM dependencies."
        run: |
          cd private-repo
          npm install

      - name: "Build release: Stable"
        run: |
          cd private-repo
          npm run build

      - name: "Create a Release Archive"
        run: |
          cd private-repo
          zip -r ../dblocks-codepro.zip .
          echo "Listing contents of the zip file:"
          unzip -l ../dblocks-codepro.zip

      - name: "Checkout Public Repo"
        uses: actions/checkout@v2
        with:
          repository: 'DBlocks-by-DPlugins/dblocks-codepro'
          token: ${{ secrets.WPSCIPTSTOKEN }}
          path: 'public-repo'

      - name: "Copy Release to Public Repo"
        run: |
          cp ${GITHUB_WORKSPACE}/dblocks-codepro.zip ${GITHUB_WORKSPACE}/public-repo/
          echo "Listing contents of the public-repo directory:"
          ls -lh ${GITHUB_WORKSPACE}/public-repo/

      - name: "Commit and Push to Public Repo"
        run: |
          cd ${GITHUB_WORKSPACE}/public-repo
          git config --local user.email "workflow@bot.com"
          git config --local user.name "WorkflowBot"
          git add dblocks-codepro.zip -f
          git commit -m "Update release archive"
          git push

      - name: "Create a GitHub Release in Public Repo"
        uses: softprops/action-gh-release@v1
        with:
          files: dblocks-codepro.zip
        env:
          GITHUB_TOKEN: ${{ secrets.WPSCIPTSTOKEN }}

      - name: "Final Verification in Public Repo"
        run: |
          cd ${GITHUB_WORKSPACE}/public-repo
          echo "Final check of the zip file contents in the public repository:"
          unzip -l dblocks-codepro.zip
