name: Sync Private to Public Repository

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  sync:
    name: "Sync private repo to public repo"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out the Private Repository"
        uses: actions/checkout@v2
        with:
          repository: 'DBlocks-by-DPlugins/dblocks-codepro--dev'
          token: ${{ secrets.WPSCIPTSTOKEN }}

      - name: "Check out the Public Repository"
        uses: actions/checkout@v2
        with:
          repository: 'DBlocks-by-DPlugins/dblocks-codepro'
          token: ${{ secrets.WPSCIPTSTOKEN }}
          path: public_repo

      - name: "Copy Files to Public Repository"
        run: |
          rsync -av --exclude='.release.yml' ./ public_repo/

      - name: "Push Changes to Public Repository"
        working-directory: public_repo
        env:
          GITHUB_TOKEN: ${{ secrets.WPSCIPTSTOKEN }}
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

          # Add and commit all changes
          git add -A
          git commit -m "Sync from private repo to public repo"

          # Push with tags
          git push origin main
          git push origin --tags
